# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peter Poliwoda
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer. IBMer. Hobbyist Game Developer. Mobile app architect. Electric guitar enthusiast.
  Curious first adopter of new tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peterpoliwoda.github.io" # the base hostname & protocol for your site
twitter_username: peterpoliwoda
github_username:  peterpoliwoda

# Build settings
markdown: kramdown
